### ISSUE TITLE
Deleting the last channel I have the app error's out and can't even get back in.

### ISSUE THREAD

**Issue by cpreston321** [zernonia/simple-log#7]
# Reproduce

- Delete a channel and then it will redirect you `/app/e935205a-8a3c-4371-a8f4-bb5be94c54a4/settings` with a blank screen.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/6619884/186167201-f21f9bf0-a122-4afb-b8bf-f8df22a9370d.png">

**Comment by cpreston321** [comment]
@zernonia Now it seems I can't even access the /app without it erroring out making it not useable with my account anymore.

**Comment by zernonia** [comment]
It should be fixed now 😁
